name: python
on:
  push:
    branches:
      - master
      - fix/*

permissions:
  id-token: write
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.13"]
    defaults:
      run:
        working-directory: python

    steps:
      - uses: actions/checkout@v6
      - name: setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: install
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ci_requirements.txt
      - name: test
        run: |
          pytest --cov=covertable --cov-report=xml
      - name: codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./python/coverage.xml
          flags: python
          verbose: true

  release:
    needs: tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    if: github.ref == 'refs/heads/master'
    name: pypi upload
    steps:
      - uses: actions/checkout@v6
      - name: setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: install
        run: |
          python -m pip install --upgrade pip setuptools wheel twine build
          python -m pip install -r ci_requirements.txt
      - name: build
        run: |
          python -m build --sdist --wheel --outdir dist/ .
      - name: check
        run: |
          twine check dist/*
      - name: upload
        run: |
          twine upload dist/* --non-interactive --skip-existing
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
